---
title: "About Me"
author: "Joy"
date: 2019-12-15T21:13:14-05:00
categories: ["R"]

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# About Me!

My name is Joy! I was born in Dallas, Texas and I moved to Austin in 2016 for college. I graduated from the University of Texas at Austin with a Bachelor of Science and Arts in Biology and a certificate in Pre-Health Professions. I'm planning on attending the PA program at the University of Texas Medical Branch, starting in July 2020. I am really passionate about healthcare and also spreading education and awareness about current topics in medicine. In my spare time, I like to read and I have been learning how to cook.


## Education

### The University of Texas at Austin -- BSA, Biology
Fall 2016 - Fall 2019 -- Cumulative GPA: 3.60, Science GPA: 3.65

### The University of Texas Medical Branch -- MPAS, Physician Assistant Studies Program
Starting in July 2020


## Work Experience

### Surgery Center at Plano Dermatology -- Medical Assistant
- Administered local numbing injections per the surgeon’s instructions
- Assisted surgeons during Mohs procedures and excisions (blotting, cutting sutures, etc)
- Bandaged patients post-operation and gave wound care instructions

### Biobricks Research Lab -- Mentor 
- Trained new research students on how to perform microbiology procedures
- Graded lab reports and oversaw students in lab
- Worked on an independent research project under the guidance of the research educator

### KD College Prep -- Intern
- Helped run day to day operations by creating daily schedules and organizing class materials
- Led the training of new student workers and educated them on their responsibilities
- Provided customer service to parents and students in person and on the phone


## Skills 

- Technical/Computer Skills: Familiar with Python (1 year), R (2 years)
- Lab Skills: Training in microbiology lab (PCR, protein purification, SDS-PAGE, Western blot analysis)
- Clinical Skills: Can administer local numbing injections, assist in Mohs surgeries and excisions
- Languages: Fluent in Mandarin

## Accomplishments 

University Honors -- Fall 2016